kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: demo
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        apiVersion: kubeadm.k8s.io/v1beta3
        kind: ClusterConfiguration
        apiServer:
          certSANs:
          - "127.0.0.1"
          - "localhost"
          - "0.0.0.0"
          - "172.31.44.150"     # <-- your EC2's private IP
    extraPortMappings:
      - containerPort: 80
        hostPort: 3000          # binding with host port
        listenAddress: "0.0.0.0"
        protocol: TCP
      - containerPort: 443
        hostPort: 4000          # binding with host port
        listenAddress: "0.0.0.0"
        protocol: TCP

  - role: worker
  - role: worker

networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443