# https://metallb.io/configuration/#defining-the-ips-to-assign-to-the-load-balancer-services 
# docker inspect --type network kind | grep -i subnet
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: default
spec:
  addresses:
  - 172.18.0.0/16 - 172.18.0.10/16