apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tutorial-appset
  namespace: default
spec:
  generators:
    - list:
        elements:
          - env: dev
          - env: prod
  template:
    metadata:
      name: "apps-{{.env}}"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: tutorial-app-of-apps
      source:
        repoURL: https://github.com/Kapil987/renovate-test1.git
        targetRevision: HEAD
        path: envs/{{.env}}
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - Validate=true
          - CreateNamespace=false
          - PrunePropagationPolicy=foreground
          - PruneLast=true